name: Automated Docker image build and push

on:
  push:
    paths:
      - 'Dockerfile'
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '36 2 * * *'

env:
  OWNER: gbxyz
  IMAGE_NAME: icann-rdap-conformance-tool-docker-image

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          username: ${{env.OWNER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@ef25336f420be2d1a49205baf41a9b88712a65a1
        with:
          images: ${{env.OWNER}}/${{env.IMAGE_NAME}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
